### ISSUE TITLE
How we can start the recording and pulling the video to local system?

### ISSUE THREAD

**Issue by Jitu1888** [PharmEasyEngg/lampo#4]
1. Need some ADB commands, how to do it through service?

**Comment by sarathpharmeasy** [comment]
Please refer the below docs @Jitu1888 :

https://appium.io/docs/en/commands/device/recording-screen/start-recording-screen/
https://appium.io/docs/en/commands/device/recording-screen/stop-recording-screen/

adb shell screenrecord /sdcard/video.mp4
adb pull /sdcard/video.mp4
